# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-30 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package_name', models.CharField(blank=True, default='', max_length=256, verbose_name='Package Name')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RepoDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.CharField(max_length=256, null=True, verbose_name='Owner Name')),
                ('repo_name', models.CharField(max_length=256, null=True, verbose_name='Repo Name')),
                ('stars_count', models.IntegerField(null=True, verbose_name='Stars Count')),
            ],
        ),
    ]
