# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-30 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_garden_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='repo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repo_package', to='report_garden_app.RepoDetails'),
        ),
    ]
